helm_install: https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
helm_install_path: "{{ansible_env.HOME}}/get_helm.sh"
root_path: "{{ansible_env.HOME}}"
workdir: "{{root_path}}/kolla-bringup"

globals_path: /etc/kolla/globals.yml
enable_central_logging: "yes"
enable_collectd: "no"
enable_grafana: "no"
enable_heat: "no"
enable_elasticsearch: "no"
enable_kibana: "no"
enable_haproxy: "no"
enable_designate: "no"
enable_ironic: "no"
enable_magnum: "no"
enable_murano: "no"
enable_neutron_lbaas: "no"
enable_octavia: "no"
enable_prometheus: "no"

mgmt_ip: 10.0.0.210
mgmt_int: enp15s1f2
neutron_int: neutron

cpu_model: Westmere
cpu_mode: custom
virt_type: kvm
