- name: check if docker-ce is installed
  yum:
    name: docker-ce
    state: installed
  become: yes
  register: docker-ce

- name: remove existing docker packages
  yum:
    name: "{{docker_packages}}"
    state: absent
  become: yes
  when: docker-ce.results[0].yumstate != 'installed'

- name: install required docker packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: yes

- name: add latest docker repo
  command: yum-config-manager --add-repo {{docker_repo}}
  become: yes
  when: docker-ce.results[0].yumstate != 'installed'

- name: install docker ce
  yum:
    name: docker-ce
    state: present
  become: yes

- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: install docker-py
  pip:
    name: docker-py
    state: present
  become: yes